# Dependencies
markdown:            kramdown
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/

# Setup
title:               "Scott's Weblog"
name:				 "Scott's Weblog"
tagline:             "The weblog of an IT pro specializing in virtualization, networking, open source, and cloud computing"
description:         "Offering technical posts and how-to articles from an IT pro specializing in virtualization, networking, open source, & cloud computing"
url:                 http://blog.scottlowe.org
baseurl:             /
paginate:            10

# About/contact
author:
  name:              Scott Lowe
  url:               https://twitter.com/scott_lowe
  email:             scott.lowe@scottlowe.org
  github:            lowescott
  twitter:           scott_lowe

# Custom vars
version:             1.0.0

# Exclude Ruby gem stuff
exclude:             ["vendor"]

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
